IF (NOT HIREDIS_INCLUDE_DIR)
  MESSAGE("-- Setting default Hiredis Include Directory")
  SET(HIREDIS_INCLUDE_DIR "/usr/local/include/hiredis")
ENDIF (NOT HIREDIS_INCLUDE_DIR)

MESSAGE("-- HIREDIS_INCLUDE_DIR\t" ${HIREDIS_INCLUDE_DIR})

INCLUDE_DIRECTORIES(${HIREDIS_INCLUDE_DIR})
LINK_DIRECTORIES(${HIREDIS_INCLUDE_DIR})
